remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Gardiner Lab Protocols
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
